Add nightly retrigger script
MetOffice/SimSys_Scripts pull request #20
Opened 2024-04-05 15:03 UTC by james-bruten-mo

A script to automatically relaunch and retrigger suites during meto nightly testing

2024-04-08 07:29 UTC, richardgilham requested changes
Mostly looks good. One typo and one query over some negative logic to look at.

2024-04-08 07:52 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +Can pass names of suites as posiional arguments. Doesn't need to be entire name,
fixed

2024-04-08 07:57 UTC, richardgilham approved these changes
Great, thanks for those. Approved.

2024-04-17 16:04 UTC, r-sharp requested changes
Lots of comments, hopefully a couple of useful ones.
Have fun 🤣

2024-04-17 16:04 UTC, r-sharp commented on nightly_testing/retrigger_nightlies.py
> +        if not run_all and not ask_yn(f"Do you want to restart {suite}"):
hmmm, dislike the -ve logic here. That and the reliance on Python NOT evaluating the 'AND' condition if the first one was False.
Is that perpetually guaranteed ?

2024-04-18 07:32 UTC, james-bruten-mo commented on nightly_testing/generate_test_suite_cron.py
>  Script which launches a rose-stem suite.
Updated the doc string and added a link to the working practices page.

It doesn't check and I think this is fine for the intention of this script - ie. only run by us. If we did check we'd likely only raise an error saying to include this term - as it is right now a KeyError will be raised saying the required term wasn't found, so not much different.

Set to use os.getlogin()

2024-04-18 07:33 UTC, james-bruten-mo commented on nightly_testing/generate_test_suite_cron.py
>  def lfric_heads_sed(wc_path):
Could be, think it's not that important and easy enough for someone to add later if required.

2024-04-18 07:33 UTC, james-bruten-mo commented on nightly_testing/generate_test_suite_cron.py
> +    rstr = f"cp -r {wc_path} {wc_path_new} ; "
This was copied from the existing lfric nightly setup. Feel free to do a change!

2024-04-18 07:35 UTC, james-bruten-mo commented on nightly_testing/generate_test_suite_cron.py
>  def generate_cron_timing_str(suite, mode):
Good point, cheers

2024-04-18 07:37 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +def check_suite_cylc8(conn):
Done

2024-04-18 07:41 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +    return {"y": True, "n": False}[rval]
Sure, returning rval.lower()=="y".
Have also added some strip()'s in there

2024-04-18 07:46 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +    _ = run_command(play_command)
I sort of agree, but the way the script is run we don't care what the output is. If a suite fails to relaunch or fails to restart a task, then we'll notice in the gui and would investigate there. Basically I initially went to add some output here but decided there was nothing useful it could tell us.

2024-04-18 07:49 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +        print(f"\rTask {i+1}/{ntasks}", end="", flush=True)
I knew that syntax - I've used itbefore (certainly in AoC problems to see if a brute force approach might finish in a reasonable time - it never does). 

I disagree about seeing the task being triggered - it would likely go too fast to make sense and you can see the retriggered ones in the gui. Also when there are >100 tasks if the HPC breaks overnight then it's not worth seeing.

2024-04-18 07:54 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +    if len(sys.argv) > 1:
I think for now this is ok as there are no other options to give (see next comment about user). Easy enough for someone to change if they want to.

2024-04-18 07:57 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +            else:
Updated the comment and your interpretation is right

2024-04-18 08:08 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +            valid_suites.append(suite)
Moved into a function

2024-04-18 08:11 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +            failed_suites[suite] = failed_tasks
Done, but not getting involved with mock at this point!

2024-04-18 08:12 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +    run_all = ask_yn("Do you want to restart all failed suites")
Not sure about touching the command line args just for this but could be done in the future

2024-04-18 08:15 UTC, james-bruten-mo commented on nightly_testing/retrigger_nightlies.py
> +        if not run_all and not ask_yn(f"Do you want to restart {suite}"):
If the 1st part is False, python won't ever look at the 2nd part - you can do something along the lines of (pseudocode):

if x is defined and x==y:
    do stuff()

I guess the negative logic isn't great but I can't see the way around it? Have you got a better suggestion?

2024-04-18 08:16 UTC, james-bruten-mo commented on nightly_testing/tests/test_generate_test_suite_cron.py
> +    ("wc_path", "expected", "new_wc"),
I way copying the approach with all the other ones in the file, including tests with multiple inputs. Very happy for a demonstration of best practices for pytest at some point but probably not in this ticket?

2024-04-18 08:31 UTC, james-bruten-mo commented
Thanks Roddy, Some changes made and some pushed back to you.

2024-04-18 08:34 UTC, james-bruten-mo commented on nightly_testing/generate_test_suite_cron.py
>  Script which launches a rose-stem suite.
Actually, the last point in line 55 had already been modified to do that so just fixed a merge conflict on that line.

2024-04-18 12:05 UTC, r-sharp commented on nightly_testing/retrigger_nightlies.py
> +        if not run_all and not ask_yn(f"Do you want to restart {suite}"):
Sadly, no. If I had a better suggestion, I'd have made it...

2024-04-18 15:28 UTC, r-sharp approved these changes
Yup, changes look good, reasons for non-changes are reasonable.

Now, how do I merge to trunk ?....
Hello ?, hello ?
Is this thing on ?
Helloo ?

2024-04-18 15:30 UTC, merged