UMPD3 checker: Check external repositories when they are modified by a branch.
MetOffice/SimSys_Scripts pull request #31
Opened 2024-06-14 18:45 UTC by AdamVoysey

Currently, UM dependencies are checked by the UMDP3 checker on the trunk.

However, in a branch, the branch diff is used rather than the source files themselves. (This means the script only checks things that are changed by a branch, not the entire source tree.) 

This in turn means changes from the other dependencies are not checked until _after_ they are on trunk in a linked ticket. (This is because the branch diff contains only the changes to the sources, not the code changes themselves - which exist in a different repository.)

This pull request modifies the script to ensure dependencies are checked with the branch, when the script identifies that either the `rose-suite.conf` file, or the `HOST_SOURCE` environment variables have been modified. In that case, it inspects the full source of the external repository, as it would do on trunk.

2024-09-04 12:13 UTC, james-bruten-mo approved these changes
I've got nothing useful to add here, happy to approve

2024-11-06 13:36 UTC, AdamVoysey commented
Can I give this PR a bump?

2024-11-08 13:18 UTC, ericaneininger commented on script_umdp3_checker/bin/umdp3_check.pl
> +    # enable trunkmode for sepecific repositories if rose-stem/rose-suite.conf
```suggestion
    # enable trunkmode for specific repositories if rose-stem/rose-suite.conf
```

2024-11-08 13:19 UTC, ericaneininger commented on script_umdp3_checker/bin/umdp3_check.pl
> +        # enable trunkmode for sepecific repositories if the environment does
```suggestion
        # enable trunkmode for specific repositories if the environment does
```

2024-11-08 13:20 UTC, ericaneininger commented on script_umdp3_checker/bin/umdp3_check.pl
> +    # If we capturede any changes, enable trunk-mode for those repositories.
```suggestion
    # If we captured any changes, enable trunk-mode for those repositories.
```

2024-11-08 13:23 UTC, ericaneininger requested changes
A couple of typos in comments with suggested change.  Otherwise all good.  Thanks.

2024-11-08 13:25 UTC, ericaneininger approved these changes

2024-11-08 13:26 UTC, merged