Replace optparse with argparse in suite_report.py
MetOffice/SimSys_Scripts pull request #34
Opened 2024-08-12 19:42 UTC by t00sa

The only script using `optparse` was `suite_report.py`.  This has been updated to use `argparse` and the script has been linted and its compliance with flake8 improved.

A before and after comparison of the output from `suite_report.py` shows no change in behaviour:

```
vdi> python suite_report.py -S ~/cylc-run/vn13.6_remove_optparse/runN/ -L /var/tmp
svn://fcm1/monc.xm_svn/casim/trunk appears to be the trunk, nothing to do!
svn://fcm1/jules.xm_svn/main/trunk appears to be the trunk, nothing to do!
svn://fcm1/moci.xm_svn/main/trunk appears to be the trunk, nothing to do!
svn://fcm1/um.xm_svn/mule/trunk appears to be the trunk, nothing to do!
svn://fcm1/utils.xm_svn/shumlib/trunk appears to be the trunk, nothing to do!
svn://fcm1/socrates.xm_svn/main/trunk appears to be the trunk, nothing to do!
svn://fcm1/ukca.xm_svn/main/trunk appears to be the trunk, nothing to do!
svn://fcm1/um.xm_svn/aux/trunk appears to be the trunk, nothing to do!
svn://fcm1/um.xm_svn/meta/trunk appears to be the trunk, nothing to do!
vdi> diff /var/tmp/trac.log ~/cylc-run/vn13.6_remove_optparse/runN/trac.log 
7c7
<  || Report Generated: || 2024/08/12 20:34:02 || 
---
>  || Report Generated: || 2024/08/12 13:53:01 ||
vdi> 
```

See also: [UM ticket 7722](https://code.metoffice.gov.uk/trac/um/ticket/7722)

2024-09-03 15:37 UTC, ericaneininger reviewed
A couple of comments/queries in-line.

2024-09-03 15:37 UTC, ericaneininger commented on suite_report.py
> +                message += [f"There were {num_interactions} projects "]
Appending a list of length one looks odd to me.  Could use `message.append(<msg>)`
Having said that this structure is also used in the method `create_approval_table()`.  Perhaps a pickiness too far!

2024-09-03 15:37 UTC, ericaneininger commented on suite_report.py
> +                    # pylint: disable=consider-using-f-string
Having made so many the conversion to f-string format statements, there just 3 older style `.format()`s left.  Why these?

2024-09-04 07:36 UTC, t00sa commented on suite_report.py
> +                print(f'{key} is :"{value}"')
I think the point of the final else is to catch any attribute in the current instance that does have a specific if test that applies a specific format.

The code isn't actually called anywhere, so I think it's just a hold-over from development and I've got a wider refactoring change that removes it entirely.

2024-09-04 07:41 UTC, t00sa commented on suite_report.py
> +                message += [f"There were {num_interactions} projects "]
I suspect there was a conscious decision not to use in-place additions rather than append() to be consistent with the sections that add multiple lines to the messages list.  I'm happy to leave it be for now.

I've got wider refactoring changes that replace the list with an io.StringIO instance to make it possible to use print to construct an output buffer.

2024-09-04 07:48 UTC, t00sa commented on suite_report.py
> +                    # pylint: disable=consider-using-f-string
Good point.  It feels like there should be a more elegant way to format these string, but it's not immediately clear to me what it is.  Perhaps they should be a property of the instance?

I'll take a look at the other pylint fstring exclusions and see if I can improve those too.

2024-09-13 09:50 UTC, ericaneininger commented on suite_report.py
> +                    # pylint: disable=consider-using-f-string
Happy to accept most of my comments will be addressed in the refactor ticket.

2024-09-13 09:51 UTC, ericaneininger approved these changes

2024-10-16 10:27 UTC, r-sharp commented on suite_report.py
> +                    # pylint: disable=consider-using-f-string
Would this be a good one to us os.path.join on instead of creating a string manually ?

2024-10-16 11:28 UTC, r-sharp requested changes
Just looking at that - there were some "things were going to get back to later..." like the verbosity level which I'm amused to see are still untouched. Any chance they could be considered in the "major refactor" you mention ?

2024-10-16 11:28 UTC, r-sharp commented on suite_report.py
> +                # pylint: disable=consider-using-f-string
hmmmmm, .... Yum !
What about breaking it into 2 lines...
bg_colour = BACKGROUND_COLOURS[self.primary_project.lower()]
trac_log.append(
    f"{{{{{{#!div style='background : {bg_colour}'"

I appreciate it's just the same thing another way, but it should (hopefully) dispose of 2 linter directives...

2024-10-16 11:28 UTC, r-sharp commented on suite_report.py
> +                " || Cylc-Review: || {0:s}/{1:s}/{2:s}/?suite={3:s} || "
Another where it might be useful to split out into multiple 'steps'
use os.path.join() to join all the parts together into a string which you assign to "sodding_path", and then use an f-string with {sodding_path} in it.

2024-10-16 11:28 UTC, r-sharp commented on suite_report.py
> +        # been added to rose-suite.conf for now
In general - are these not dead yet ? does the UM trac.log still report on compare wallclock and compare output tests ?

2024-10-16 11:28 UTC, r-sharp commented on suite_report.py
>                      )
```
                trac_log.append(
                    "This rose-stem suite included multiple "
                    + f"branches in {len(self.multi_branches.keys())}"
                    + " projects:"
```
Might get rid of the linter directives - I /think/ the line isn't too long...

2024-10-16 11:28 UTC, r-sharp commented on suite_report.py
> +        # pylint: disable=broad-exception-caught
Is this needed **here** because it looks like it might have been an attempt to re-enable broad-exception-caught ?

2024-11-08 14:57 UTC, ericaneininger commented on suite_report.py
> +                    # pylint: disable=consider-using-f-string
I would always prefer to see `os.path.join()` rather than a string with `/`s in.  It's then platform safe should someone try to run on Windows.

2025-01-05 09:55 UTC, yaswant commented on suite_report.py
> +# pylint: disable=too-many-instance-attributes
I think this is a hangover from the early days.  Would it make sense to have a `pylintrc` file and add all skippable standards there instead of adding them inside the code in multiple places?

2025-01-05 10:13 UTC, yaswant commented on suite_report.py
> +            except Exception:
Perhaps be more specific what exception is expected here or spit the error message inside the except block?

2025-01-20 09:18 UTC, t00sa commented on suite_report.py
> +                message += [f"There were {num_interactions} projects "]
I think we're in agreement that it's not perhaps the most elegant of bits of code - for reasons lost to history - but it works and it's probably good enough for now.

2025-01-20 09:21 UTC, t00sa commented on suite_report.py
> +                    # pylint: disable=consider-using-f-string
A better python 3 method is to use pathlib.Path because this allows the use of a slash to join paths while retaining platform independence.

2025-01-20 09:30 UTC, t00sa commented on suite_report.py
> +   UM repository. When making changes, please ensure the changes are
Good point.  Comment changed to reference the github repo.

2025-01-20 09:34 UTC, t00sa commented on suite_report.py
> +# pylint: disable=too-many-lines
I've gone for both.

Warnings that encompass the entire source file - such as complaints about the number of lines or excessive sizes of multiple functions - go at the top.

Anything more limited in scope gets a disable/enable pair of surrounding the suspect bit of code.  This makes it possible to ignore the specific issue for now, whilst also marking it up for future refactoring work.

2025-01-20 09:37 UTC, t00sa commented on suite_report.py
> +# pylint: disable=too-many-instance-attributes
No, this is intentional: I've resolved the easy linting issues and marked up the more complex ones with disable/enable blocks, with the idea that they can be resolved later.  I don't think we want to disable these warnings entirely because they usually flag up genuine problems with the code.

2025-01-20 09:47 UTC, t00sa commented on suite_report.py
> +                # pylint: disable=consider-using-f-string
Good idea.  Just fixed it.

2025-01-20 09:59 UTC, t00sa commented on suite_report.py
> +        status_counts = status_counts or defaultdict(int)
There is a reason for this: using containers in default arguments is not recommended because it effectively makes them persist across function calls.  So:

```py
def f1(x, keep=[]):
    keep.append(x)
    print(keep)

def f2(x, keep=None):
    keep = keep or []
    keep.append(x)
    print(keep)

f1(1)
f1(2)

f2(3)
f2(4)
```

Gives:

```
[1]
[1, 2]
[3]
[4]
```

Which is why the second round of check-and-initialise is necessary.

2025-01-20 10:04 UTC, t00sa commented on suite_report.py
>                      )
I'll double check.  If we do go down the ruff/black route, we'll probably want to bump the maximum line length up in the linter anyway.

2025-01-20 10:07 UTC, t00sa commented on suite_report.py
>                      )
Looks fine, so I've made the change.

2025-01-20 10:11 UTC, t00sa commented on suite_report.py
> +        # pylint: disable=broad-exception-caught
Good spot.  Looks like a copy-and-paste mistake to me

2025-01-20 17:26 UTC, yaswant approved these changes
@t00sa one minor comment: can you blackify the script please? Once #51 is merged, this script will need reformatting again to pass the CI.

2025-01-27 15:35 UTC, t00sa commented on suite_report.py
> +        # been added to rose-suite.conf for now
The UM does.  It's marginally helpful but it feels like it's something we might want to revisit at some point.  Maybe when Chris Bennett has got cylc suite task monitoring working?

2025-01-27 16:41 UTC, t00sa commented on suite_report.py
> +            except Exception:
The problem is that the code itself uses `raise Exception` at various points, so it's not possible to differentiate between errors without refactoring the code.  This why I've opted to disable the warnings rather than resolve the underlying problem in this change.

2025-01-27 18:33 UTC, t00sa commented on suite_report.py
> +                " || Cylc-Review: || {0:s}/{1:s}/{2:s}/?suite={3:s} || "
Sensible advice.  Added to the latest revision.

2025-01-27 18:38 UTC, t00sa commented
@yaswant I'm going to suggest that we don't run black on the code base as part of this change, but instead create a follow-on ticket.  That would allow us to add the revision to the `.git-blame-ignore-revs` to prevent formatting changes from breaking `git blame`

2025-03-20 16:55 UTC, james-bruten-mo approved these changes
Looking through Roddys comments, it seems like these have all been done, so I think this is good to go

2025-03-20 16:57 UTC, merged