Fix suite mode
MetOffice/SimSys_Scripts pull request #4
Opened 2023-10-30 10:13 UTC by AdamVoysey

Following on from UM [#7266](https://code.metoffice.gov.uk/trac/um/ticket/7266), the UMPD3 checker no longer has quite the same test coverage that it once did. This is because the script is no longer in the same repository as the rest of the code, so its use of FCM on the locations will have to be different in some situations. (Specifically when the script is in "suite mode". When you run the script on the command line and point it at a branch/working copy, it still works as expected, because it retrieves the FCM metadata from the working copy.)

This pull request make the changes the UMDP3 checker scripts to instead use a local copy of the files (created by the `script_{{SCRIPTS.platform}}_extract_source` task) when in suite mode. This avoids the need to use FCM.

The result is the UMDP3 checker will now check from the extracted sources:

1. The UM code (as was previously checked)
2. The scripts code (which previously was in the UM repository)
3. Shumlib code (which was always handled by the UMDP3 checker, but was previously being run manually upon Shumlib changes - so this is now automatic for the first time)
4. UKCA code (which still follows UMDP3, and was previously checked; but for which checking was lost when it moved to its own repository)
5. meta (which is new, but which probably should be checked)

2023-11-10 14:28 UTC, richardgilham requested changes
Changes generally look OK with a reasonable amount of commenting and error trapping.

Passing back briefly for...

- Inline comment regarding JULES etc
- Confirm this has been tested in both modes to ensure it runs OK (even if it fails on finding non-compliant code)

2023-11-10 14:28 UTC, richardgilham commented on script_umdp3_checker/bin/umdp3_check.pl
> +        my @extracts = ( "", "um", "shumlib", "meta", "ukca" );
Any reason this can't be extended to take in JULES, SOCRATES and CASIM right now?

2023-11-10 15:34 UTC, AdamVoysey commented on script_umdp3_checker/bin/umdp3_check.pl
> +        my @extracts = ( "", "um", "shumlib", "meta", "ukca" );
In terms of the UMDP3 checker script itself running - no. (In fact I did test during the change development.) However, this would currently throw a lot of additional warnings, with a good number of them being false-positives.

For JULES and SOCRATES, its mostly a case of some minor differences in the code style, such as how code owners are handled. The script absolutely can be fixed to understand these differences in the same way as is done for Shumlib already.

If that is something you wish to explore, it certainly can be done - but is probably best left for a different change/pull request.

In the case of CASIM, it might be a step too far, as the code seems to have been developed against a slightly more divergent set of coding standards than the other code. Again, it can be applied if you want to, but this is likely to lead to a lot of changes/code churn in CASIM to make it follow a UMDP3-like style - which is a political decision to some extent.

2023-11-10 16:41 UTC, AdamVoysey commented
To confirm, the change was tested in "suite mode" by running the UM rose stem with the `script_spice_export_git_scripts` task trigger-edited to point to this branch. (Cylc review output is [here](http://fcm1/cylc-review/taskjobs/avoysey?&suite=um_trunk_github_scripts&no_fuzzy_time=0&tasks=script_spice_umdp3_checker)). Also tested on the command line against a working copy for non-"suite mode".

2023-11-13 11:15 UTC, richardgilham approved these changes

2023-11-29 16:18 UTC, r-sharp reviewed
Got some comments about style of code added..

2023-11-30 13:38 UTC, AdamVoysey commented on script_umdp3_checker/bin/umdp3_check.pl
> +        unless ( $returncode == 0 ) {
now changed to `if ( $returncode != 0 ) {`

2023-11-30 13:39 UTC, AdamVoysey commented on script_umdp3_checker/bin/umdp3_check.pl
> +            die
As above, now changed to `if ( $returncode != 0 ) {`

2023-12-01 12:44 UTC, r-sharp approved these changes
Changes look fine to me.

2023-12-01 12:45 UTC, merged

2023-12-01 12:45 UTC, r-sharp commented
Changes merged in.