7 kgo update script
MetOffice/SimSys_Scripts pull request #8
Opened 2024-01-24 14:01 UTC by james-bruten-mo

These changes allow the kgo update scripts to work with cylc 7 and cylc8. There are changes to allow the scripts to find variables*.cylc files as well as variables*.rc files and for the wrapper shell scripts to work for lfricinputs kgo installation as well as for UM. 

The first commit is a straight copy of the scripts from the UM trunk.

2024-01-24 14:13 UTC, james-bruten-mo commented
Also worth noting that I've installed (and cleaned up) some lfricinputs kgo with this PR and tested in the UM by installing the kgo for UM:#7271.

2024-01-31 15:30 UTC, jennyhickson reviewed
generally looks okay. The need to pass the variables extension around makes it look more complicated, but nice to cover old and new cylc in one place. Not sure about the use of F for the variable_extension, but you've already used E and V for other things so can't think what would make a good alternative!

2024-01-31 16:12 UTC, james-bruten-mo commented on kgo_updates/kgo_update/kgo_update.py
> +        variables_path = os.path.join(suite_dir,
We've agreed that we don't need to protect the old inputs suite so removed that 2nd part. The suite will also raise an error if site isn't defined to protect this part now.

2024-01-31 17:47 UTC, jennyhickson reviewed
Looking cleaner :)

2024-01-31 17:47 UTC, jennyhickson commented on kgo_updates/kgo_update/kgo_update.py
> +    vars_file = "variables.rc"
variables_extension needed?

2024-02-01 08:40 UTC, james-bruten-mo commented on kgo_updates/kgo_update/kgo_update.py
> +    vars_file = "variables.rc"
Done

2024-02-05 10:26 UTC, richardgilham requested changes
Couple of trivial typos, but otherwise looks good.

2024-02-05 10:26 UTC, richardgilham commented on kgo_updates/kgo_update/meto_run_kgo_script.sh
> +# If Spice has kgo updates
Basically the same code 3 times, so could be encapsulated/looped at some point in the future.

2024-02-05 10:26 UTC, richardgilham commented on kgo_updates/kgo_update/kgo_update.py
> +    # This order is important as both kgo_variables.cylc and variables.cylc
That's a bit yucky but well commented and probably a proportionate solution.

2024-02-05 10:34 UTC, james-bruten-mo commented on kgo_updates/kgo_update/kgo_update.py
> +This script will parse the rose-ana-comparisons.db produces by a valid
Done

2024-02-05 10:34 UTC, james-bruten-mo commented on kgo_updates/kgo_update/kgo_update.py
> +=> --new-release     Only for use by the UM Systems Team when releasing a new
Done

2024-02-05 10:36 UTC, james-bruten-mo commented on kgo_updates/kgo_update/meto_run_kgo_script.sh
> +# If Spice has kgo updates
Unfortunately just enough platform specific changes to make this awkward

2024-02-05 10:37 UTC, james-bruten-mo commented on kgo_updates/kgo_update/kgo_update.py
> +    # This order is important as both kgo_variables.cylc and variables.cylc
There's a newer version of this function post Jennys review

2024-02-05 11:04 UTC, richardgilham commented on kgo_updates/kgo_update/kgo_update.py
> +    # This order is important as both kgo_variables.cylc and variables.cylc
My fault- missed it when looking at the commit diffs vs the overall change.

2024-02-05 11:05 UTC, richardgilham approved these changes

2024-02-05 11:06 UTC, merged