Create a new copyright test
MetOffice/SimSys_Scripts pull request #9
Opened 2024-02-02 14:09 UTC by AdamVoysey

Associated with UM ticket [#7483](https://code.metoffice.gov.uk/trac/um/ticket/7483), this pull request adds the new python script to test copyright against a set of pre-defined templates.

2024-02-09 09:26 UTC, james-bruten-mo commented on script_copyright_checker/bin/copyright_checker.py
> +                    found_template = True
Instead of using the found_template variable can you just return True here and similarly below. Then return False at the end. Has the benefit of not doing unnecessary loops.

2024-02-09 09:28 UTC, james-bruten-mo requested changes
Thanks for those first changes. I think this is in a pretty good place now and much easier to edit and improve as we go forward than the UMDP3 script so thanks. Just one other request in the check_compliance function

2024-02-09 14:02 UTC, AdamVoysey commented on script_copyright_checker/bin/copyright_checker.py
> +                    found_template = True
I have now implemented this as well

2024-02-09 14:04 UTC, james-bruten-mo approved these changes

2024-02-09 14:04 UTC, james-bruten-mo commented
Thanks Adam, approved from me

2024-02-14 16:24 UTC, GiorgiaLine approved these changes
That is a lot of templates!
Changes look good. Now I have an itch to go and make all the MO copyright statements uniform...
Approved for merge, I'll hit the button once the UM side is on.

2024-02-16 16:43 UTC, merged